// 15 high-CPM YouTube channel brand kits — same shape as YT_BRANDS in
// youtube-engine.mjs, plus channel-specific fields (handle, voice, slots,
// description, themeBank) that the flow, banner generator, and branding
// pusher all read.
//
// Niche/CPM basis (2026, US-audience): finance $30-50, insurance ~$38,
// legal/tax $15-35, B2B/business $15-35, AI/tech $8-20, health $10-18.
// All channels: English, channel country US, US-primetime slots (ET).
// Voices: Edge TTS, one distinct voice per channel.

export const COUNTRY = 'US';

export const BRANDS = [
  {
    slug: 'quotequarry',
    label: 'QUOTE QUARRY',
    handle: '@quotequarry302',
    niche: 'Stoicism & daily motivation',
    cpmTier: 'main channel',
    accent: '#F5E31C', bg: '#0A0A0A', ink: '#FFFFFF',
    eyebrow: 'DAILY WISDOM // QUOTE QUARRY',
    tagline: 'Quarry your best self.',
    keyword: 'stoic quotes', kwShort: 'stoic wisdom', theme: 'Stoicism',
    niches: ['stoicism', 'self mastery', 'mental strength'],
    authority: 'Stoicism Philosophy',
    tags: ['stoicism', 'stoic wisdom', 'motivation', 'discipline', 'mindset', 'self improvement', 'mental strength', 'philosophy', 'success mindset', 'inner peace'],
    musicFeels: ['epic', 'inspir', 'heroic'],
    voice: 'am_michael',
    slots: [],
    longSlot: '14:30',
    active: true,
    themeBank: ['silent behaviors that make people respect you', 'things to cut out of your life quietly', 'signs someone is secretly testing you', 'things you must do alone to become stronger', 'rules that protect you from toxic people', 'phrases fake friends use', 'things you should never apologize for', 'stop caring about these things', 'habits of mentally unbreakable people', 'ways to beat manipulators without fighting', 'habits that separate winners from dreamers', 'signs you are becoming mentally stronger']
  },
  {
    slug: 'investors-compass',
    label: "INVESTOR'S COMPASS",
    handle: '@InvestorsCompass-c7h', active: true,
    niche: 'Investing psychology & market wisdom',
    cpmTier: '$30-50 (finance #1 niche)',
    accent: '#E8C15A', bg: '#0A1128', ink: '#F2EEE3',
    eyebrow: 'MARKET WISDOM // INVESTOR\'S COMPASS',
    tagline: 'Conviction over panic.',
    keyword: 'investing wisdom', kwShort: 'investing wisdom', theme: 'Investing',
    niches: ['investing psychology', 'stock market wisdom', 'long term wealth'],
    authority: 'Investing Psychology',
    tags: ['investing', 'stock market', 'warren buffett', 'financial education', 'money mindset', 'compounding', 'value investing', 'market psychology', 'wealth building', 'finance', 'investment strategy', 'stock market for beginners'],
    voice: 'bm_george',
    musicFeels: ['calming', 'inspir', 'mystical'], // premium, calm-confident market wisdom
    slots: ['12:05', '16:05', '23:35'], longSlot: '21:30', // long: 5:30p ET
    description: 'Investing wisdom and stock market psychology in 60 seconds. Timeless principles from Buffett, Munger and Bogle — patience, compounding, and buying fear instead of selling it. New Shorts daily. Build conviction, not panic. Subscribe for daily investing wisdom.',
    themeBank: ['investor mistakes that cost fortunes', 'rules Warren Buffett never breaks', 'signs you are panic selling', 'habits of patient investors', 'things to never do in a market crash', 'compounding explained through small habits', 'contrarian moves that paid off', 'questions to ask before buying any stock', 'signs a stock is hype not value', 'what rich investors do during a downturn', 'beginner investing rules that never change', 'psychology traps every trader falls into']
  },
  {
    slug: 'money-rulebook',
    label: 'THE MONEY RULEBOOK',
    handle: '@themoneyrulebook-p4y', active: true,
    niche: 'Personal finance rules & money habits',
    cpmTier: '$25-45 (personal finance)',
    accent: '#3DDC97', bg: '#101314', ink: '#EAF6EF',
    eyebrow: 'MONEY RULES // THE MONEY RULEBOOK',
    tagline: 'Rules beat motivation.',
    keyword: 'money rules', kwShort: 'money rules', theme: 'Money',
    niches: ['personal finance', 'money habits', 'saving systems'],
    authority: 'Personal Finance',
    tags: ['personal finance', 'money tips', 'saving money', 'financial freedom', 'budgeting', 'wealth habits', 'money management', 'financial literacy', 'pay yourself first', 'money mindset', 'financial planning', 'build wealth'],
    voice: 'bm_daniel',
    musicFeels: ['bright', 'uplifting', 'grooving'], // clean, confident money-rules energy
    slots: ['12:35', '16:35', '00:05'], longSlot: '22:30', // long: 6:30p ET
    description: 'Money rules that quietly build wealth — one principle per Short. Pay yourself first, automate savings, kill lifestyle creep. Personal finance in 60 seconds, new rule every day. Subscribe and let the rules compound.',
    themeBank: ['money rules rich people never break', 'salary habits that change your life', 'silent ways you leak money', 'pay yourself first explained', 'lifestyle creep warning signs', 'rules for your first $10,000', 'things broke people buy first', 'automation habits that build wealth', 'money rules by age 30', 'signs you are budgeting wrong', 'financial red flags in your 20s', 'wealth killers hiding in plain sight']
  },
  {
    slug: 'debt-free-doctrine',
    label: 'DEBT-FREE DOCTRINE',
    handle: '@debtfreedoctrine', active: true, // renamed + clean handle + verified 2026-09-06
    niche: 'Debt payoff & credit smarts',
    cpmTier: '$20-40 (credit/loans advertisers)',
    accent: '#FF5A4E', bg: '#14100E', ink: '#F6EDEA',
    eyebrow: 'DEBT-FREE // DEBT-FREE DOCTRINE',
    tagline: 'Owe nothing. Own everything.',
    keyword: 'debt freedom', kwShort: 'debt freedom', theme: 'Debt',
    niches: ['debt payoff', 'credit score', 'loan traps'],
    authority: 'Debt Freedom',
    tags: ['debt free', 'pay off debt', 'credit score', 'credit cards', 'debt payoff journey', 'financial freedom', 'loan tips', 'debt snowball', 'money tips', 'financial literacy', 'interest rates', 'no more debt'],
    voice: 'am_fenrir',
    musicFeels: ['driving', 'action', 'heroic'], // determined, no-excuses debt payoff energy
    slots: ['13:05', '17:05', '00:35'], longSlot: '01:30', // long: 9:30p ET
    description: 'Debt freedom starts with the right rules, not more hustle. Credit scores, loan traps, and payoff order — explained in 60 seconds. New Shorts daily until debt is a word you forget. Subscribe and start owing nothing.',
    themeBank: ['debt payoff mistakes that cost thousands', 'credit score moves banks hate', 'loan traps disguised as help', 'rules for your first credit card', 'signs a loan is predatory', 'snowball vs avalanche made simple', 'things to never finance', 'habits that quietly raise your credit score', 'what collectors hope you never learn', 'debt-free people never do these', 'interest math banks hide', 'how to negotiate debt like a pro']
  },
  {
    slug: 'escrow-estate',
    label: 'ESCROW & ESTATE',
    handle: '@escrowestate-p3x', active: false, // fully ready (renamed+verified) — parked 09-06, add anytime
    niche: 'Real estate wisdom & property',
    cpmTier: '$20-35 (real estate)',
    accent: '#D98E4A', bg: '#171210', ink: '#F5EFE7',
    eyebrow: 'PROPERTY WISDOM // ESCROW & ESTATE',
    tagline: 'Own land. Sleep well.',
    keyword: 'real estate wisdom', kwShort: 'real estate', theme: 'Property',
    niches: ['real estate', 'first home buying', 'property investing'],
    authority: 'Real Estate',
    tags: ['real estate', 'buying a home', 'first time home buyer', 'mortgage tips', 'property investment', 'house hacking', 'real estate investing', 'renting vs buying', 'home loans', 'property market', 'real estate tips', 'wealth through property'],
    voice: 'bm_george',
    slots: ['23:05'],
    description: 'Real estate wisdom in 60 seconds — mortgages, first homes, rental math, and the property rules banks hope you never question. New Shorts daily. Own land, sleep well. Subscribe for daily property wisdom.',
    themeBank: ['first home mistakes that cost six figures', 'mortgage truths banks soften', 'rent vs buy decided by one number', 'signs a property is a money pit', 'questions to ask before signing', 'house rules rich buyers follow', 'red flags at an open house', 'how location quietly sets your net worth', 'renting can make you rich if', 'closing costs nobody warns you about', 'property inspection secrets', 'what appraisers actually look for']
  },
  {
    slug: 'policy-brief',
    label: 'THE POLICY BRIEF',
    handle: '@thepolicybrief-t9u', active: false, // fully ready (renamed+verified) — parked 09-06, add anytime
    niche: 'Insurance explained simply',
    cpmTier: '~$38 (insurance sleeper CPM)',
    accent: '#58A6C9', bg: '#0E1418', ink: '#EAF2F6',
    eyebrow: 'COVER CHECK // THE POLICY BRIEF',
    tagline: 'Read the fine print here.',
    keyword: 'insurance explained', kwShort: 'insurance', theme: 'Insurance',
    niches: ['insurance explained', 'coverage gaps', 'claims wisdom'],
    authority: 'Insurance Education',
    tags: ['insurance explained', 'life insurance', 'health insurance', 'car insurance', 'home insurance', 'insurance tips', 'coverage', 'claims', 'financial protection', 'insurance policy', 'term life', 'financial planning'],
    voice: 'am_michael',
    slots: ['02:35'],
    description: 'Insurance explained in 60 seconds — coverage gaps, claim secrets, and the fine print that saves families. Life, health, auto and home, one policy rule at a time. New Shorts daily. Subscribe before you need it.',
    themeBank: ['insurance mistakes that void your claim', 'what life insurance really covers', 'claims adjusters hope you never ask', 'coverage gaps that bankrupt families', 'term vs whole life made simple', 'car insurance rules after a crash', 'health insurance terms decoded', 'when to increase your coverage', 'denied claim next moves', 'hidden perks already in your policy', 'renters insurance myths', 'disability insurance the quiet essential']
  },
  {
    slug: 'old-money-code',
    label: 'OLD MONEY CODE',
    handle: '@oldmoneycode-g2x', active: false, // fully ready (renamed+verified) — parked 09-06, add anytime
    niche: 'Old money habits & quiet wealth',
    cpmTier: '$15-30 (finance-adjacent, huge reach)',
    accent: '#D9C7A7', bg: '#12100C', ink: '#F3EDE2',
    eyebrow: 'QUIET WEALTH // OLD MONEY CODE',
    tagline: 'Wealth whispers.',
    keyword: 'old money habits', kwShort: 'old money', theme: 'Quiet Wealth',
    niches: ['old money habits', 'quiet luxury', 'generational wealth'],
    authority: 'Old Money Philosophy',
    tags: ['old money', 'old money habits', 'quiet luxury', 'old money aesthetic', 'generational wealth', 'elegance', 'classy lifestyle', 'wealth habits', 'success habits', 'old money rules', 'style', 'self improvement'],
    voice: 'af_heart',
    slots: ['13:05'],
    description: 'Old money habits, quiet luxury, and the rules of understated wealth — in 60 seconds. How generational wealth thinks, spends, and stays silent. New Shorts daily. Subscribe and learn why wealth whispers.',
    themeBank: ['old money rules for spending', 'habits of generational wealth', 'why the rich buy boring things', 'quiet luxury is a behavior', 'things old money never flaunt', 'how heirs are raised differently', 'old money morning rituals', 'signs of new money vs old money', 'the asset first rule', 'elegance is restraint explained', 'old money rules for dressing', 'family rules that preserve fortunes']
  },
  {
    slug: 'founders-margin',
    label: 'FOUNDERS MARGIN',
    handle: '@FoundersMargin',
    niche: 'Entrepreneurship & lean business',
    cpmTier: '$15-35 (B2B/business)',
    accent: '#9EE04F', bg: '#0C1210', ink: '#EFF6EA',
    eyebrow: 'FOUNDER LOGIC // FOUNDERS MARGIN',
    tagline: 'Margin is the mission.',
    keyword: 'founder lessons', kwShort: 'founder lessons', theme: 'Founders',
    niches: ['entrepreneurship', 'startup lessons', 'lean business'],
    authority: 'Entrepreneurship',
    tags: ['entrepreneurship', 'startup tips', 'founder mistakes', 'business lessons', 'small business', 'bootstrap', 'business mindset', 'side hustle', 'first customer', 'profit margin', 'business growth', 'solopreneur'],
    voice: 'am_adam',
    slots: ['21:35'],
    description: 'Founder lessons in 60 seconds — pricing, first customers, cash flow, and the startup mistakes that kill good ideas. Business wisdom for people who build. New Shorts daily. Subscribe and protect your margin.',
    themeBank: ['founder mistakes that kill startups', 'rules for your first customer', 'pricing mistakes that bleed margin', 'bootstrap rules that force profit', 'signs your business model is broken', 'cash flow truths nobody teaches', 'why boring businesses win', 'when to quit your job numbers', 'marketing on a zero budget', 'lessons from failed founders', 'one product beats ten ideas', 'hire slow rules for founders']
  },
  {
    slug: 'closing-table',
    label: 'THE CLOSING TABLE',
    handle: '@TheClosingTable',
    niche: 'Sales & negotiation psychology',
    cpmTier: '$20-40 (B2B/sales)',
    accent: '#E14D6B', bg: '#120C10', ink: '#F6EBEF',
    eyebrow: 'DEAL PSYCHOLOGY // THE CLOSING TABLE',
    tagline: 'Every conversation is a deal.',
    keyword: 'negotiation psychology', kwShort: 'negotiation', theme: 'Negotiation',
    niches: ['negotiation', 'sales psychology', 'persuasion'],
    authority: 'Sales Psychology',
    tags: ['negotiation', 'sales tips', 'persuasion', 'sales psychology', 'closing techniques', 'business negotiation', 'influence', 'communication skills', 'deal making', 'salary negotiation', 'psychology of selling', 'dark psychology'],
    voice: 'am_onyx',
    slots: ['22:35'],
    description: 'Negotiation psychology in 60 seconds — the moves, the silences, and the frames that close deals at work, in business, and in life. New Shorts daily. Subscribe and never accept the first number again.',
    themeBank: ['negotiation moves that flip leverage', 'silence as a weapon explained', 'phrases that kill a deal', 'salary negotiation scripts that work', 'anchors decide the outcome', 'how to read a buyer real intent', 'objection handling in three steps', 'power questions that close', 'signs you are being manipulated in a deal', 'the flinch and other classics', 'win-win is a trap sometimes', 'walk away like a professional']
  },
  {
    slug: 'corner-office',
    label: 'CORNER OFFICE MIND',
    handle: '@CornerOfficeMind',
    niche: 'Leadership & management wisdom',
    cpmTier: '$18-35 (B2B/management)',
    accent: '#C0C6D0', bg: '#0D1017', ink: '#EFF1F4',
    eyebrow: 'LEAD // CORNER OFFICE MIND',
    tagline: 'Lead quietly. Win loudly.',
    keyword: 'leadership wisdom', kwShort: 'leadership', theme: 'Leadership',
    niches: ['leadership', 'management skills', 'office politics'],
    authority: 'Leadership',
    tags: ['leadership', 'management tips', 'leadership skills', 'boss tips', 'career advice', 'office politics', 'team management', 'executive presence', 'workplace wisdom', 'professional growth', 'people skills', 'promotion tips'],
    voice: 'bm_daniel',
    slots: ['23:35'],
    description: 'Leadership wisdom in 60 seconds — managing up, running meetings, earning respect, and the quiet moves that get people promoted. New Shorts daily. Subscribe and lead without the noise.',
    themeBank: ['boss mistakes that lose the team', 'rules for managing your manager', 'meeting moves that show authority', 'how leaders say no gracefully', 'signs of a weak leader', 'promotion habits nobody notices', 'delegation without losing control', 'feedback that actually changes people', 'office politics without the games', 'first 90 days as a new manager', 'quiet authority is a skill', 'why great leaders hire people who argue']
  },
  {
    slug: 'tax-shield',
    label: 'TAX SHIELD',
    handle: '@TaxShield',
    niche: 'Small-business tax & legal principles',
    cpmTier: '$15-35 (tax/legal education)',
    accent: '#4ECDC4', bg: '#0B1210', ink: '#EAF5F3',
    eyebrow: 'KEEP MORE // TAX SHIELD',
    tagline: 'Earn it. Keep it.',
    keyword: 'tax tips', kwShort: 'tax smarts', theme: 'Tax',
    niches: ['tax education', 'small business taxes', 'deductions explained'],
    authority: 'Tax Education',
    tags: ['tax tips', 'small business taxes', 'deductions', 'tax deductions', 'llc tips', 'bookkeeping', 'tax season', 'self employment taxes', 'keep more money', 'tax planning', 'business finance', 'accounting basics'],
    voice: 'am_michael',
    slots: ['00:05'],
    description: 'Tax principles in 60 seconds — deductions, LLC basics, bookkeeping habits, and the rules that help earners keep more of what they make. Education, not advice. New Shorts daily. Subscribe and build your shield.',
    themeBank: ['deduction myths that trigger audits', 'LLC truths simplified', 'bookkeeping habits that save tax season', 'expenses people forget to track', 'self employed money rules', 'quarterly taxes explained simply', 'records the tax office loves', 'home office rules decoded', 'why the rich hire accountants early', 'receipts rule everything', 'entity choice in plain english', 'legal writes offs vs myths']
  },
  {
    slug: 'ai-observer',
    label: 'THE AI OBSERVER',
    handle: '@TheAIObserver',
    niche: 'AI & future tech',
    cpmTier: '$8-20 (AI/tech, fastest growth)',
    accent: '#39D5FF', bg: '#05090F', ink: '#E8F6FC',
    eyebrow: 'FUTURE PROOF // THE AI OBSERVER',
    tagline: "See the shift before it's obvious.",
    keyword: 'ai explained', kwShort: 'AI', theme: 'AI',
    niches: ['artificial intelligence', 'future tech', 'ai tools'],
    authority: 'AI & Tech',
    tags: ['artificial intelligence', 'ai', 'ai tools', 'future tech', 'technology', 'ai news', 'machine learning', 'ai jobs', 'chatgpt', 'automation', 'tech explained', 'future of work'],
    voice: 'af_heart',
    slots: ['21:05'],
    description: 'AI explained in 60 seconds — the tools, the shifts, and the jobs changing first. Understand the future before it replaces the unprepared. New Shorts daily. Subscribe and stay future proof.',
    themeBank: ['jobs ai changes first', 'ai tools that feel illegal to know', 'signs a task will be automated', 'how to future proof your career', 'ai myths everyone still believes', 'prompts that feel like cheating', 'what agentic ai really means', 'skills ai makes more valuable', 'the last jobs to be automated', 'ai red flags to spot fake content', 'small businesses winning with ai', 'questions to ask before trusting ai']
  },
  {
    slug: 'deep-work-os',
    label: 'DEEP WORK OS',
    handle: '@DeepWorkOS',
    niche: 'Focus & productivity systems',
    cpmTier: '$10-20 (SaaS/productivity advertisers)',
    accent: '#C8B6FF', bg: '#0E0B14', ink: '#F0EBFA',
    eyebrow: 'FOCUS MODE // DEEP WORK OS',
    tagline: 'Attention is the asset.',
    keyword: 'deep work', kwShort: 'deep work', theme: 'Focus',
    niches: ['deep work', 'productivity systems', 'focus habits'],
    authority: 'Productivity',
    tags: ['deep work', 'productivity', 'focus', 'time management', 'study tips', 'productivity systems', 'attention span', 'work smarter', 'pomodoro', 'procrastination', 'digital minimalism', 'cal newport'],
    voice: 'am_onyx',
    slots: ['00:35'],
    description: 'Deep work in 60 seconds — focus systems, anti-distraction rules, and the habits of people who produce more by doing less. New Shorts daily. Subscribe and install your focus operating system.',
    themeBank: ['focus rules that beat willpower', 'phone habits destroying your attention', 'morning systems of high performers', 'how to start when you overdistracted', 'deep work blocks explained', 'signs you are busy not productive', 'rules for your first deep work hour', 'distraction detox weekend', 'why multitasking is a scam', 'shutdown rituals that end the day', 'environment beats discipline', 'procrastination decoded in 60 seconds']
  },
  {
    slug: 'longevity-code',
    label: 'THE LONGEVITY CODE',
    handle: '@TheLongevityCode',
    niche: 'Healthspan & longevity habits',
    cpmTier: '$10-18 (health, huge watch time)',
    accent: '#7ED957', bg: '#0A100C', ink: '#EDF6E8',
    eyebrow: 'LONG GAME // THE LONGEVITY CODE',
    tagline: 'Add life to years.',
    keyword: 'longevity habits', kwShort: 'longevity', theme: 'Longevity',
    niches: ['longevity', 'healthspan', 'daily health habits'],
    authority: 'Longevity',
    tags: ['longevity', 'health tips', 'healthspan', 'healthy habits', 'wellness', 'biohacking', 'exercise science', 'nutrition tips', 'aging well', 'sleep health', 'preventive health', 'energy'],
    voice: 'af_heart',
    slots: ['01:05'],
    description: 'Longevity habits in 60 seconds — sleep, movement, food, and the small daily choices that add decades. Science made simple, one habit at a time. New Shorts daily. Subscribe and play the long game.',
    themeBank: ['daily habits that add years', 'what blue zones actually do', 'strength training after 40 rules', 'sleep is the cheapest medicine', 'food rules longevity doctors follow', 'signs your body is asking for help', 'walking is underrated science', 'stress aging you faster', 'morning light and your body clock', 'metabolic health decoded', 'habits quietly stealing your energy', ' screenings worth doing yearly']
  },
  {
    slug: 'iron-discipline',
    label: 'IRON DISCIPLINE',
    handle: '@IronDiscipline',
    niche: 'Gym & training motivation',
    cpmTier: '$8-15 (fitness, massive Shorts reach)',
    accent: '#CCFF00', bg: '#050505', ink: '#F2F2F2',
    eyebrow: 'NO EXCUSES // IRON DISCIPLINE',
    tagline: 'The iron never lies.',
    keyword: 'gym motivation', kwShort: 'gym discipline', theme: 'Iron',
    niches: ['gym motivation', 'training discipline', 'no excuses fitness'],
    authority: 'Fitness',
    tags: ['gym motivation', 'fitness motivation', 'workout discipline', 'training hard', 'no excuses', 'gym life', 'self discipline', 'mindset', 'consistency', 'grind mode', 'mens fitness', 'transformation'],
    voice: 'am_fenrir',
    slots: ['02:05'],
    description: 'Gym motivation with a spine — discipline over motivation, consistency over hype, one rep at a time. New Shorts daily. The iron never lies. Subscribe and show up anyway.',
    themeBank: ['rules of showing up daily', 'excuses the gym deletes', 'training when nobody claps', 'discipline is a muscle too', 'what six months of consistency does', 'hard truths about transformation', 'the two day rule explained', 'training the mind first', 'why slow reps build strong men', 'rest is part of the program', 'motivation follows action', 'become the person who never skips']
  },
  {
    slug: 'sleep-architect',
    label: 'THE SLEEP ARCHITECT',
    handle: '@TheSleepArchitect',
    niche: 'Sleep & recovery science',
    cpmTier: '$10-18 (health/wellness)',
    accent: '#8C9EFF', bg: '#080A14', ink: '#ECEFFB',
    eyebrow: 'LIGHTS OUT // THE SLEEP ARCHITECT',
    tagline: 'Win tomorrow tonight.',
    keyword: 'sleep better', kwShort: 'sleep science', theme: 'Sleep',
    niches: ['sleep science', 'recovery', 'evening routines'],
    authority: 'Sleep Science',
    tags: ['sleep tips', 'sleep science', 'better sleep', 'insomnia help', 'recovery', 'evening routine', 'deep sleep', 'circadian rhythm', 'sleep hygiene', 'rest', 'wellness tips', 'night routine'],
    voice: 'af_heart',
    slots: ['01:35'],
    description: 'Sleep science in 60 seconds — evening rules, deep sleep triggers, and the recovery habits that rebuild your brain and body. New Shorts daily, right before bed. Subscribe and win tomorrow tonight.',
    themeBank: ['evening habits that wreck deep sleep', 'rules for falling asleep faster', 'caffeine math nobody does', 'your phone and your melatonin', 'the wind down hour protocol', 'why you wake at 3am', 'naps that help vs hurt', 'sleep debt is real science', 'bedroom design for deep sleep', 'what one bad night really does', 'temperature is the sleep switch', 'morning light sets your night']
  }
];

export const bySlug = Object.fromEntries(BRANDS.map(b => [b.slug, b]));
